// Generated by scripts/import-page-themes.mjs. Do not edit by hand; change the list in the script.
// Colours, fonts, radius and shadows live in src/app/page-themes.css under [data-page-theme].

export type PageTheme = {
  id: ThemeId
  name: string
  pro: boolean
}

export const themes = [
  {
    id: "vercel",
    name: "Monochrome",
    pro: false
  },
  {
    id: "clean-slate",
    name: "Clean Slate",
    pro: false
  },
  {
    id: "caffeine",
    name: "Caffeine",
    pro: false
  },
  {
    id: "bubblegum",
    name: "Bubblegum",
    pro: true
  },
  {
    id: "neo-brutalism",
    name: "Neo Brutalism",
    pro: true
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    pro: true
  },
  {
    id: "kodama-grove",
    name: "Kodama Grove",
    pro: true
  },
  {
    id: "sunset-horizon",
    name: "Sunset Horizon",
    pro: true
  },
  {
    id: "vintage-paper",
    name: "Vintage Paper",
    pro: true
  },
  {
    id: "claymorphism",
    name: "Claymorphism",
    pro: true
  },
  {
    id: "starry-night",
    name: "Starry Night",
    pro: true
  },
  {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    pro: true
  }
] as const

export type ThemeId = (typeof themes)[number]["id"]

export const defaultThemeId: ThemeId = "vercel"

export function getTheme(id: string | null | undefined): PageTheme {
  return themes.find((theme) => theme.id === id) ?? themes[0]
}
